name: Lenovo Sign Task Script AUTO RUN at 00:10 CST

on:
  schedule:
    - cron: '01 16 * * *'  # 每天北京时间 12:05 运行，一般延迟1h20min左右
  workflow_dispatch:  # 可手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 或根据你的版本调整

      - name: Clone private config repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/codeking01/private-config.git
          ls -la private-config/config
          cat private-config/config/config.toml || echo "配置读取失败"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # 可选，或者你自己写的依赖安装命令

      - name: Save config hash before run # 记录配置hash是否变化
        id: save_hash
        run: |
          sha256sum private-config/config/config.toml > before_hash.txt

      - name: Run script
        run: |
          export CONFIG_FILE=private-config/config/config.toml # 导入配置路径
          python lenovo_sign.py  # 替换为你的脚本文件名

      - name: Compare hash and commit if changed # 判断记录配置hash是否变化
        run: |
          sha256sum private-config/config/config.toml > after_hash.txt
          if ! diff before_hash.txt after_hash.txt > /dev/null; then
            echo "Config changed, committing..."
            cd private-config
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@github.com"
            git add config/config.toml
            git commit -m "Auto update: config.toml changed after script run"
            git push
          else
            echo "No config change detected."
          fi
