name: Lenovo Sign Task Script AUTO RUN at 00:10 CST

on:
  schedule:
    - cron: '10 16 * * *'  # 每天北京时间 00:10 运行
  workflow_dispatch:  # 可手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 或根据你的版本调整

      - name: Clone private config repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/codeking01/private-config.git
          ls -la private-config/config
          cat private-config/config/config.toml || echo "配置读取失败"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # 可选，或者你自己写的依赖安装命令

      - name: Run script
        run: |
          export CONFIG_FILE=private-config/config/config.toml # 导入配置路径
          python lenovo_sign.py  # 替换为你的脚本文件名